# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/xxtea

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/xxtea

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/xxtea/CMakeFiles /home/ubuntu/xxtea/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/xxtea/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xxtea

# Build rule for target.
xxtea: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xxtea
.PHONY : xxtea

# fast build rule for target.
xxtea/fast:
	$(MAKE) -f CMakeFiles/xxtea.dir/build.make CMakeFiles/xxtea.dir/build
.PHONY : xxtea/fast

base64.o: base64.c.o

.PHONY : base64.o

# target to build an object file
base64.c.o:
	$(MAKE) -f CMakeFiles/xxtea.dir/build.make CMakeFiles/xxtea.dir/base64.c.o
.PHONY : base64.c.o

base64.i: base64.c.i

.PHONY : base64.i

# target to preprocess a source file
base64.c.i:
	$(MAKE) -f CMakeFiles/xxtea.dir/build.make CMakeFiles/xxtea.dir/base64.c.i
.PHONY : base64.c.i

base64.s: base64.c.s

.PHONY : base64.s

# target to generate assembly for a file
base64.c.s:
	$(MAKE) -f CMakeFiles/xxtea.dir/build.make CMakeFiles/xxtea.dir/base64.c.s
.PHONY : base64.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/xxtea.dir/build.make CMakeFiles/xxtea.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/xxtea.dir/build.make CMakeFiles/xxtea.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/xxtea.dir/build.make CMakeFiles/xxtea.dir/main.c.s
.PHONY : main.c.s

md5.o: md5.c.o

.PHONY : md5.o

# target to build an object file
md5.c.o:
	$(MAKE) -f CMakeFiles/xxtea.dir/build.make CMakeFiles/xxtea.dir/md5.c.o
.PHONY : md5.c.o

md5.i: md5.c.i

.PHONY : md5.i

# target to preprocess a source file
md5.c.i:
	$(MAKE) -f CMakeFiles/xxtea.dir/build.make CMakeFiles/xxtea.dir/md5.c.i
.PHONY : md5.c.i

md5.s: md5.c.s

.PHONY : md5.s

# target to generate assembly for a file
md5.c.s:
	$(MAKE) -f CMakeFiles/xxtea.dir/build.make CMakeFiles/xxtea.dir/md5.c.s
.PHONY : md5.c.s

xxtea.o: xxtea.c.o

.PHONY : xxtea.o

# target to build an object file
xxtea.c.o:
	$(MAKE) -f CMakeFiles/xxtea.dir/build.make CMakeFiles/xxtea.dir/xxtea.c.o
.PHONY : xxtea.c.o

xxtea.i: xxtea.c.i

.PHONY : xxtea.i

# target to preprocess a source file
xxtea.c.i:
	$(MAKE) -f CMakeFiles/xxtea.dir/build.make CMakeFiles/xxtea.dir/xxtea.c.i
.PHONY : xxtea.c.i

xxtea.s: xxtea.c.s

.PHONY : xxtea.s

# target to generate assembly for a file
xxtea.c.s:
	$(MAKE) -f CMakeFiles/xxtea.dir/build.make CMakeFiles/xxtea.dir/xxtea.c.s
.PHONY : xxtea.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... xxtea"
	@echo "... base64.o"
	@echo "... base64.i"
	@echo "... base64.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... md5.o"
	@echo "... md5.i"
	@echo "... md5.s"
	@echo "... xxtea.o"
	@echo "... xxtea.i"
	@echo "... xxtea.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

